<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>GPTUsageWidget</AssemblyName>
    <RootNamespace>GPTUsageWidget</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>..\assets\GPTUsageWidget.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
